name: package_scripts
description: Scripts for packaging Markora plugins
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  crypto: ^3.0.5
  path: ^1.9.0 